# Generated by Django 6.0.5 on 2026-05-29 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_pincode'),
        ('payments', '0002_remove_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_signature',
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='CREATED', max_length=20),
        ),
    ]
