# Generated by Django 6.0.6 on 2026-06-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
