# Generated by Django 6.0.6 on 2026-06-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_razorpay_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cart_snapshot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
