--
-- PostgreSQL database dump
--

\restrict yicELkftehF3ePpJBR0K6nhnNNxaqmOFjTplZGGRgrJCeZrrEXfI7T8Pxuo7G41

-- Dumped from database version 18.4 (Ubuntu 18.4-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.4 (Ubuntu 18.4-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(10) NOT NULL,
    full_name character varying(150) NOT NULL,
    is_email_verified boolean NOT NULL
);


ALTER TABLE public.accounts_user OWNER TO postgres;

--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_user_groups OWNER TO postgres;

--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_user_user_permissions OWNER TO postgres;

--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_userprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_userprofile (
    id bigint NOT NULL,
    phone character varying(15),
    address text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.accounts_userprofile OWNER TO postgres;

--
-- Name: accounts_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts_cart; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.carts_cart (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.carts_cart OWNER TO postgres;

--
-- Name: carts_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.carts_cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts_cartitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.carts_cartitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    cart_id bigint NOT NULL,
    variant_id bigint NOT NULL,
    CONSTRAINT carts_cartitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.carts_cartitem OWNER TO postgres;

--
-- Name: carts_cartitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.carts_cartitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_cartitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: home_brandstory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.home_brandstory (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    subtitle character varying(100) NOT NULL,
    description text NOT NULL,
    image character varying(100) NOT NULL,
    feature_1 character varying(100) NOT NULL,
    feature_2 character varying(100) NOT NULL,
    feature_3 character varying(100) NOT NULL,
    feature_4 character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.home_brandstory OWNER TO postgres;

--
-- Name: home_brandstory_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.home_brandstory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.home_brandstory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_order (
    id bigint NOT NULL,
    order_id character varying(20) NOT NULL,
    payment_method character varying(20) NOT NULL,
    payment_status character varying(20) NOT NULL,
    status character varying(30) NOT NULL,
    shipping_status character varying(30) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    shipping_charge numeric(10,2) NOT NULL,
    discount numeric(10,2) NOT NULL,
    total numeric(10,2) NOT NULL,
    courier_partner character varying(100),
    tracking_number character varying(100),
    estimated_delivery date,
    shipped_at timestamp with time zone,
    delivered_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    refund_status character varying(20) NOT NULL,
    refund_method character varying(20),
    refund_reference character varying(100),
    refunded_at timestamp with time zone,
    user_id bigint NOT NULL
);


ALTER TABLE public.orders_order OWNER TO postgres;

--
-- Name: orders_order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_orderitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_orderitem (
    id bigint NOT NULL,
    product_name character varying(255) NOT NULL,
    product_image character varying(100),
    variant_id integer NOT NULL,
    sku character varying(100),
    size character varying(50) NOT NULL,
    color character varying(50) NOT NULL,
    price numeric(10,2) NOT NULL,
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    CONSTRAINT orders_orderitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.orders_orderitem OWNER TO postgres;

--
-- Name: orders_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_orderreturn; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_orderreturn (
    id bigint NOT NULL,
    reason character varying(255) NOT NULL,
    comment text,
    status character varying(30) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    order_id bigint NOT NULL
);


ALTER TABLE public.orders_orderreturn OWNER TO postgres;

--
-- Name: orders_orderreturn_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_orderreturn ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_orderreturn_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_shipmentevent; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_shipmentevent (
    id bigint NOT NULL,
    status character varying(100) NOT NULL,
    message text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    order_id bigint NOT NULL
);


ALTER TABLE public.orders_shipmentevent OWNER TO postgres;

--
-- Name: orders_shipmentevent_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_shipmentevent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_shipmentevent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_shippingaddress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_shippingaddress (
    id bigint NOT NULL,
    full_name character varying(120) NOT NULL,
    phone character varying(10) NOT NULL,
    email character varying(254) NOT NULL,
    address_line_1 character varying(255) NOT NULL,
    address_line_2 character varying(255),
    city character varying(100) NOT NULL,
    state character varying(100) NOT NULL,
    postal_code character varying(6) NOT NULL,
    country character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    order_id bigint NOT NULL
);


ALTER TABLE public.orders_shippingaddress OWNER TO postgres;

--
-- Name: orders_shippingaddress_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_shippingaddress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_shippingaddress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments_payment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payments_payment (
    id bigint NOT NULL,
    razorpay_order_id character varying(100) NOT NULL,
    razorpay_payment_id character varying(100),
    amount numeric(10,2) NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    order_id bigint
);


ALTER TABLE public.payments_payment OWNER TO postgres;

--
-- Name: payments_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payments_payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_brand; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_brand (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(50) NOT NULL,
    logo character varying(100),
    is_active boolean NOT NULL
);


ALTER TABLE public.products_brand OWNER TO postgres;

--
-- Name: products_brand_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products_brand ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_brand_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_category (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(50) NOT NULL,
    image character varying(100),
    is_active boolean NOT NULL
);


ALTER TABLE public.products_category OWNER TO postgres;

--
-- Name: products_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_color; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_color (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(50) NOT NULL,
    hex_code character varying(10)
);


ALTER TABLE public.products_color OWNER TO postgres;

--
-- Name: products_color_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products_color ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_color_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_inventorylog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_inventorylog (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    transaction_type character varying(20) NOT NULL,
    quantity integer NOT NULL,
    note text,
    variant_id bigint NOT NULL
);


ALTER TABLE public.products_inventorylog OWNER TO postgres;

--
-- Name: products_inventorylog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products_inventorylog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_inventorylog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_product (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    slug character varying(50) NOT NULL,
    description text NOT NULL,
    material character varying(255),
    minimum_order_quantity integer NOT NULL,
    status character varying(20) NOT NULL,
    is_featured boolean NOT NULL,
    is_active boolean NOT NULL,
    meta_title character varying(255),
    meta_description text,
    brand_id bigint NOT NULL,
    category_id bigint NOT NULL,
    CONSTRAINT products_product_minimum_order_quantity_check CHECK ((minimum_order_quantity >= 0))
);


ALTER TABLE public.products_product OWNER TO postgres;

--
-- Name: products_productimage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_productimage (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    image character varying(100) NOT NULL,
    is_primary boolean NOT NULL,
    product_id uuid NOT NULL
);


ALTER TABLE public.products_productimage OWNER TO postgres;

--
-- Name: products_productimage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products_productimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_productimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_productvariant; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_productvariant (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    sku character varying(100) NOT NULL,
    wholesale_price numeric(10,2) NOT NULL,
    stock_quantity integer NOT NULL,
    is_active boolean NOT NULL,
    color_id bigint NOT NULL,
    product_id uuid NOT NULL,
    size_id bigint NOT NULL,
    CONSTRAINT products_productvariant_stock_quantity_check CHECK ((stock_quantity >= 0))
);


ALTER TABLE public.products_productvariant OWNER TO postgres;

--
-- Name: products_productvariant_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products_productvariant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_productvariant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_size; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_size (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(20) NOT NULL,
    sort_order integer NOT NULL,
    CONSTRAINT products_size_sort_order_check CHECK ((sort_order >= 0))
);


ALTER TABLE public.products_size OWNER TO postgres;

--
-- Name: products_size_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products_size ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_size_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wishlist_wishlist; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wishlist_wishlist (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id uuid NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.wishlist_wishlist OWNER TO postgres;

--
-- Name: wishlist_wishlist_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wishlist_wishlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wishlist_wishlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user (id, password, last_login, is_superuser, first_name, last_name, is_staff, is_active, date_joined, email, phone, full_name, is_email_verified) FROM stdin;
1	pbkdf2_sha256$1200000$8LWkLLFqQLwiDztvPL1tad$2DBobpP3rApcahI2k5K1FbrRqUPSi0X28p/OL9X1PEY=	2026-06-22 06:39:29.798092+00	t			t	t	2026-06-21 20:29:10.843513+00	agvasu2015@gmail.com	7799692015		f
2	pbkdf2_sha256$1200000$djB6iGeuxoEilqeRk0mkpM$gEyb1AQbB46u1MwRBQ4K2cp04bXij8gFWWBZtvH5YeE=	2026-06-22 09:20:41.940335+00	f			f	t	2026-06-21 20:30:50.451928+00	agvasup123@gmail.com	9010380748	Nandu	f
3	pbkdf2_sha256$1200000$3t5rbTz7jdRsIdv0L1HKNT$xJLjs68Rc9LZDZOpgosUpdLUzB2h/V9GdZhYWfZZxSM=	2026-06-22 09:22:15.32125+00	f			f	t	2026-06-22 09:22:14.688706+00	atagur2015@gmail.com	9347157437	teja	f
\.


--
-- Data for Name: accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: accounts_userprofile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_userprofile (id, phone, address, created_at, updated_at, user_id) FROM stdin;
1	\N	\N	2026-06-21 20:29:11.466593+00	2026-06-21 20:29:11.466605+00	1
2	\N	\N	2026-06-21 20:30:51.070902+00	2026-06-21 20:30:51.070916+00	2
3	\N	\N	2026-06-22 09:22:15.307073+00	2026-06-22 09:22:15.307084+00	3
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add brand	6	add_brand
22	Can change brand	6	change_brand
23	Can delete brand	6	delete_brand
24	Can view brand	6	view_brand
25	Can add color	8	add_color
26	Can change color	8	change_color
27	Can delete color	8	delete_color
28	Can view color	8	view_color
29	Can add size	13	add_size
30	Can change size	13	change_size
31	Can delete size	13	delete_size
32	Can view size	13	view_size
33	Can add category	7	add_category
34	Can change category	7	change_category
35	Can delete category	7	delete_category
36	Can view category	7	view_category
37	Can add product	10	add_product
38	Can change product	10	change_product
39	Can delete product	10	delete_product
40	Can view product	10	view_product
41	Can add product image	11	add_productimage
42	Can change product image	11	change_productimage
43	Can delete product image	11	delete_productimage
44	Can view product image	11	view_productimage
45	Can add product variant	12	add_productvariant
46	Can change product variant	12	change_productvariant
47	Can delete product variant	12	delete_productvariant
48	Can view product variant	12	view_productvariant
49	Can add inventory log	9	add_inventorylog
50	Can change inventory log	9	change_inventorylog
51	Can delete inventory log	9	delete_inventorylog
52	Can view inventory log	9	view_inventorylog
53	Can add cart	14	add_cart
54	Can change cart	14	change_cart
55	Can delete cart	14	delete_cart
56	Can view cart	14	view_cart
57	Can add cart item	15	add_cartitem
58	Can change cart item	15	change_cartitem
59	Can delete cart item	15	delete_cartitem
60	Can view cart item	15	view_cartitem
61	Can add order	16	add_order
62	Can change order	16	change_order
63	Can delete order	16	delete_order
64	Can view order	16	view_order
65	Can add order item	17	add_orderitem
66	Can change order item	17	change_orderitem
67	Can delete order item	17	delete_orderitem
68	Can view order item	17	view_orderitem
69	Can add order return	18	add_orderreturn
70	Can change order return	18	change_orderreturn
71	Can delete order return	18	delete_orderreturn
72	Can view order return	18	view_orderreturn
73	Can add shipment event	19	add_shipmentevent
74	Can change shipment event	19	change_shipmentevent
75	Can delete shipment event	19	delete_shipmentevent
76	Can view shipment event	19	view_shipmentevent
77	Can add Shipping Address	20	add_shippingaddress
78	Can change Shipping Address	20	change_shippingaddress
79	Can delete Shipping Address	20	delete_shippingaddress
80	Can view Shipping Address	20	view_shippingaddress
81	Can add payment	21	add_payment
82	Can change payment	21	change_payment
83	Can delete payment	21	delete_payment
84	Can view payment	21	view_payment
85	Can add Brand Story	22	add_brandstory
86	Can change Brand Story	22	change_brandstory
87	Can delete Brand Story	22	delete_brandstory
88	Can view Brand Story	22	view_brandstory
89	Can add user	23	add_user
90	Can change user	23	change_user
91	Can delete user	23	delete_user
92	Can view user	23	view_user
93	Can add user profile	24	add_userprofile
94	Can change user profile	24	change_userprofile
95	Can delete user profile	24	delete_userprofile
96	Can view user profile	24	view_userprofile
97	Can add wishlist	25	add_wishlist
98	Can change wishlist	25	change_wishlist
99	Can delete wishlist	25	delete_wishlist
100	Can view wishlist	25	view_wishlist
\.


--
-- Data for Name: carts_cart; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.carts_cart (id, created_at, updated_at, user_id) FROM stdin;
1	2026-06-21 21:13:40.893761+00	2026-06-21 21:13:40.893773+00	2
2	2026-06-21 21:39:20.778355+00	2026-06-21 21:39:20.77837+00	1
\.


--
-- Data for Name: carts_cartitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.carts_cartitem (id, quantity, created_at, cart_id, variant_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-06-21 21:04:37.150428+00	1	UnityThreads	1	[{"added": {}}]	22	1
2	2026-06-21 21:05:37.658458+00	1	UnityThreads	2	[]	22	1
3	2026-06-21 21:06:45.879684+00	1	Men	1	[{"added": {}}]	7	1
4	2026-06-21 21:07:08.168758+00	1	white	1	[{"added": {}}]	8	1
5	2026-06-21 21:07:37.289917+00	1	medium	1	[{"added": {}}]	13	1
6	2026-06-21 21:09:21.34286+00	1	UT	1	[{"added": {}}]	6	1
7	2026-06-21 21:11:02.007718+00	1	M	2	[{"changed": {"fields": ["Name"]}}]	13	1
8	2026-06-21 21:11:23.844959+00	344e7c6a-fe10-4e9b-b29a-34ab5e190b2f	Product object (344e7c6a-fe10-4e9b-b29a-34ab5e190b2f)	1	[{"added": {}}, {"added": {"name": "product image", "object": "Premium Hooide"}}, {"added": {"name": "product image", "object": "Premium Hooide"}}, {"added": {"name": "product variant", "object": "Premium Hooide - M - white"}}]	10	1
9	2026-06-21 21:12:38.847761+00	1	Hoodies	2	[{"changed": {"fields": ["Name", "Slug"]}}]	7	1
10	2026-06-21 21:15:21.972642+00	1	ORD-20260621-0001	2	[{"changed": {"fields": ["Status", "Shipping status", "Estimated delivery", "Shipped at"]}}]	16	1
11	2026-06-21 21:16:13.003147+00	1	ORD-20260621-0001	2	[{"changed": {"fields": ["Status", "Shipping status"]}}]	16	1
12	2026-06-21 21:17:00.608947+00	1	UnityThreads	2	[]	22	1
13	2026-06-21 21:40:32.402496+00	1	UnityThreads	2	[{"changed": {"fields": ["Image"]}}]	22	1
14	2026-06-21 21:41:14.612303+00	344e7c6a-fe10-4e9b-b29a-34ab5e190b2f	Product object (344e7c6a-fe10-4e9b-b29a-34ab5e190b2f)	2	[{"changed": {"name": "product variant", "object": "Premium Hooide - M - white", "fields": ["Wholesale price"]}}]	10	1
15	2026-06-22 07:12:33.907785+00	344e7c6a-fe10-4e9b-b29a-34ab5e190b2f	Product object (344e7c6a-fe10-4e9b-b29a-34ab5e190b2f)	2	[{"added": {"name": "product image", "object": "Premium Hooide"}}, {"changed": {"name": "product image", "object": "Premium Hooide", "fields": ["Image"]}}, {"changed": {"name": "product image", "object": "Premium Hooide", "fields": ["Image"]}}]	10	1
16	2026-06-22 07:13:58.604945+00	1	Hoodies	2	[{"changed": {"fields": ["Image"]}}]	7	1
17	2026-06-22 07:14:24.002467+00	1	Hoodies	2	[{"changed": {"fields": ["Image"]}}]	7	1
18	2026-06-22 07:56:13.276012+00	2	T-shirts	1	[{"added": {}}]	7	1
19	2026-06-22 07:58:22.797714+00	9958cb62-2b72-42d4-8400-1b8203b6bf20	Product object (9958cb62-2b72-42d4-8400-1b8203b6bf20)	1	[{"added": {}}, {"added": {"name": "product image", "object": "Pure Cotton"}}, {"added": {"name": "product image", "object": "Pure Cotton"}}, {"added": {"name": "product image", "object": "Pure Cotton"}}, {"added": {"name": "product variant", "object": "Pure Cotton - M - white"}}]	10	1
20	2026-06-22 08:06:42.577326+00	b471635f-72c1-4603-af6d-b3eb6471ebc1	Product object (b471635f-72c1-4603-af6d-b3eb6471ebc1)	1	[{"added": {}}, {"added": {"name": "product image", "object": "Casual Wear"}}, {"added": {"name": "product image", "object": "Casual Wear"}}, {"added": {"name": "product variant", "object": "Casual Wear - M - white"}}]	10	1
21	2026-06-22 08:39:19.250916+00	9958cb62-2b72-42d4-8400-1b8203b6bf20	Product object (9958cb62-2b72-42d4-8400-1b8203b6bf20)	3		10	1
22	2026-06-22 08:39:19.25097+00	344e7c6a-fe10-4e9b-b29a-34ab5e190b2f	Product object (344e7c6a-fe10-4e9b-b29a-34ab5e190b2f)	3		10	1
23	2026-06-22 08:41:06.826227+00	4	ORD-20260622-0001	3		16	1
24	2026-06-22 08:41:06.82628+00	3	ORD-20260621-0003	3		16	1
25	2026-06-22 08:41:06.826298+00	2	ORD-20260621-0002	3		16	1
26	2026-06-22 08:41:06.826313+00	1	ORD-20260621-0001	3		16	1
27	2026-06-22 08:41:38.97979+00	1	Hoodies	2	[{"changed": {"fields": ["Image"]}}]	7	1
28	2026-06-22 08:41:55.758464+00	1	Hoodies	2	[{"changed": {"fields": ["Image"]}}]	7	1
29	2026-06-22 08:42:38.39056+00	3	Shirts	1	[{"added": {}}]	7	1
30	2026-06-22 08:42:59.231834+00	4	Trousers	1	[{"added": {}}]	7	1
31	2026-06-22 08:43:22.69129+00	b471635f-72c1-4603-af6d-b3eb6471ebc1	Product object (b471635f-72c1-4603-af6d-b3eb6471ebc1)	2	[{"changed": {"fields": ["Is featured"]}}]	10	1
32	2026-06-22 08:43:30.981143+00	b471635f-72c1-4603-af6d-b3eb6471ebc1	Product object (b471635f-72c1-4603-af6d-b3eb6471ebc1)	2	[{"changed": {"fields": ["Status"]}}]	10	1
33	2026-06-22 08:43:59.175646+00	b471635f-72c1-4603-af6d-b3eb6471ebc1	Product object (b471635f-72c1-4603-af6d-b3eb6471ebc1)	2	[{"changed": {"fields": ["Status"]}}]	10	1
34	2026-06-22 08:44:33.328929+00	b471635f-72c1-4603-af6d-b3eb6471ebc1	Product object (b471635f-72c1-4603-af6d-b3eb6471ebc1)	2	[{"changed": {"fields": ["Status"]}}, {"changed": {"name": "product variant", "object": "Casual Wear - M - white", "fields": ["Stock quantity"]}}]	10	1
35	2026-06-22 08:45:15.105607+00	1	UnityThreads	2	[{"changed": {"fields": ["Image"]}}]	22	1
36	2026-06-22 08:47:11.52583+00	43d232be-d06b-44b7-b963-8fca106023f1	Product object (43d232be-d06b-44b7-b963-8fca106023f1)	1	[{"added": {}}, {"added": {"name": "product image", "object": "Pure Cotton"}}, {"added": {"name": "product variant", "object": "Pure Cotton - M - white"}}]	10	1
37	2026-06-22 08:48:44.878403+00	2f762341-8651-4372-9fd2-79187f4cc21c	Product object (2f762341-8651-4372-9fd2-79187f4cc21c)	1	[{"added": {}}, {"added": {"name": "product image", "object": "Linen_Club"}}, {"added": {"name": "product variant", "object": "Linen_Club - M - white"}}]	10	1
38	2026-06-22 08:50:54.405924+00	de3889cc-940c-44c3-a698-e91782b9ccef	Product object (de3889cc-940c-44c3-a698-e91782b9ccef)	1	[{"added": {}}, {"added": {"name": "product image", "object": "Pure Cotton"}}, {"added": {"name": "product image", "object": "Pure Cotton"}}, {"added": {"name": "product variant", "object": "Pure Cotton - M - white"}}]	10	1
39	2026-06-22 08:51:28.810015+00	de3889cc-940c-44c3-a698-e91782b9ccef	Product object (de3889cc-940c-44c3-a698-e91782b9ccef)	2	[{"changed": {"name": "product image", "object": "Pure Cotton", "fields": ["Is primary"]}}]	10	1
40	2026-06-22 08:52:06.074743+00	b471635f-72c1-4603-af6d-b3eb6471ebc1	Product object (b471635f-72c1-4603-af6d-b3eb6471ebc1)	2	[{"changed": {"name": "product image", "object": "Casual Wear", "fields": ["Is primary"]}}]	10	1
41	2026-06-22 08:52:37.282412+00	b471635f-72c1-4603-af6d-b3eb6471ebc1	Product object (b471635f-72c1-4603-af6d-b3eb6471ebc1)	3		10	1
42	2026-06-22 08:53:45.962549+00	2d9c407c-0183-4c36-aab1-3a4064dae43b	Product object (2d9c407c-0183-4c36-aab1-3a4064dae43b)	1	[{"added": {}}, {"added": {"name": "product image", "object": "Pure Cotton"}}, {"added": {"name": "product variant", "object": "Pure Cotton - M - white"}}]	10	1
43	2026-06-22 08:59:11.587127+00	2d9c407c-0183-4c36-aab1-3a4064dae43b	Product object (2d9c407c-0183-4c36-aab1-3a4064dae43b)	2	[{"added": {"name": "product image", "object": "Pure Cotton"}}]	10	1
44	2026-06-22 08:59:48.69987+00	2	T-shirts	2	[{"changed": {"fields": ["Image"]}}]	7	1
45	2026-06-22 09:00:06.093911+00	2	T-shirts	2	[{"changed": {"fields": ["Image"]}}]	7	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	products	brand
7	products	category
8	products	color
9	products	inventorylog
10	products	product
11	products	productimage
12	products	productvariant
13	products	size
14	carts	cart
15	carts	cartitem
16	orders	order
17	orders	orderitem
18	orders	orderreturn
19	orders	shipmentevent
20	orders	shippingaddress
21	payments	payment
22	home	brandstory
23	accounts	user
24	accounts	userprofile
25	wishlist	wishlist
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-06-21 13:53:45.686578+00
2	contenttypes	0002_remove_content_type_name	2026-06-21 13:53:45.69274+00
3	auth	0001_initial	2026-06-21 13:53:45.717456+00
4	auth	0002_alter_permission_name_max_length	2026-06-21 13:53:45.722313+00
5	auth	0003_alter_user_email_max_length	2026-06-21 13:53:45.727632+00
6	auth	0004_alter_user_username_opts	2026-06-21 13:53:45.733376+00
7	auth	0005_alter_user_last_login_null	2026-06-21 13:53:45.738925+00
8	auth	0006_require_contenttypes_0002	2026-06-21 13:53:45.741085+00
9	auth	0007_alter_validators_add_error_messages	2026-06-21 13:53:45.746592+00
10	auth	0008_alter_user_username_max_length	2026-06-21 13:53:45.751807+00
11	auth	0009_alter_user_last_name_max_length	2026-06-21 13:53:45.75727+00
12	auth	0010_alter_group_name_max_length	2026-06-21 13:53:45.763163+00
13	auth	0011_update_proxy_permissions	2026-06-21 13:53:45.768145+00
14	auth	0012_alter_user_first_name_max_length	2026-06-21 13:53:45.773467+00
15	accounts	0001_initial	2026-06-21 13:53:45.805894+00
16	admin	0001_initial	2026-06-21 13:53:45.820358+00
17	admin	0002_logentry_remove_auto_add	2026-06-21 13:53:45.827987+00
18	admin	0003_logentry_add_action_flag_choices	2026-06-21 13:53:45.836346+00
19	products	0001_initial	2026-06-21 13:53:45.942653+00
20	carts	0001_initial	2026-06-21 13:53:45.974609+00
21	home	0001_initial	2026-06-21 13:53:45.980552+00
22	orders	0001_initial	2026-06-21 13:53:46.125827+00
23	payments	0001_initial	2026-06-21 13:53:46.14909+00
24	sessions	0001_initial	2026-06-21 13:53:46.156672+00
25	wishlist	0001_initial	2026-06-21 13:53:46.184073+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
bzzdoq1ro1lw1fh3w7z0kpkbr1hhjmwo	.eJxVjMsOwiAQRf-FtSFFHtN26d5vIAwMFjVgoE00xn_Xmi50e8-558msW-bJLo2qTYGNTLDd74bOXyivIJxdPhXuS55rQr4qfKONH0ug62Fz_wKTa9PnrUkao50HFBA6pTVFkqpD5QAQsVfSUxTRi8H0e6lQ9mEYIkAMYIQw32ij1lLJlu63VB9s7F5vjvw_Iw:1wbPwe:L9NM8IKiwgOrR7lOjr2l2uOpjH-Tl7e2t8kcGthnQdM	2026-07-05 21:43:12.993333+00
4exg976j32ahu0o0ng9n1o3mjls5idsk	.eJxVj80KwjAQhN8l51ISjUnqzd4Fix68hU12tVVpStKCP_juWqygt2Hmm4F5MAtDX9shUbQNsiWbsezXc-DP1I4BnqA9htyHto-Ny0ckn9KUrwPSpZzYv4EaUv1uK0-F55wOUhhZGE3CKQGCS64K5SUgCqG1QeNJK-3mCyikcwgo9AGF5ONoopSa0Fq6dk28sSXPWIR7iB3cbIj4ffCRO1ndzarcdtWeqg17vgBp3E4X:1wbPzC:VnhyHJZhW7Ec1BHiwtagerDOaa53EyqojShALVeGxOI	2026-07-05 21:45:50.12711+00
htdqsfsnwv5hid8g05f2k2qga9bpi4rm	.eJxVjMsOwiAQRf-FtSFFHtN26d5vIAwMFjVgoE00xn_Xmi50e8-558msW-bJLo2qTYGNTLDd74bOXyivIJxdPhXuS55rQr4qfKONH0ug62Fz_wKTa9PnrUkao50HFBA6pTVFkqpD5QAQsVfSUxTRi8H0e6lQ9mEYIkAMYIQw32ij1lLJlu63VB9s7F5vjvw_Iw:1wbYJd:ARbjytX7r6auqu7PNQdIn8eZVPbDUO2sXSOK8KajljY	2026-07-06 06:39:29.800722+00
fiulcjtuz0sewgknzctvtil9j92x90md	.eJxVjEEOwiAQRe_C2hAIDIJL956BDDMgVQNJaVeNd9cmXej2v_f-JiKuS43ryHOcWFyEEaffLSE9c9sBP7Ddu6TelnlKclfkQYe8dc6v6-H-HVQc9VuDU5oDgQ1ULFhyqpydK8ieHQMFjYrAUNZZE3AqHDxkEzRoxcUHJ94f6KE4Gg:1wbar9:6-mVqy83YcKYCtVAx4QPZIV40afR72JfR-Ue278Td-k	2026-07-06 09:22:15.323636+00
\.


--
-- Data for Name: home_brandstory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.home_brandstory (id, title, subtitle, description, image, feature_1, feature_2, feature_3, feature_4, is_active, created_at, updated_at) FROM stdin;
1	UnityThreads	Wear your identity @ Unite your style.	Unitythreads was created from a simple belief - what you wear should represent who you are. Every thread is designed to connect identity, culture, and confidence into one powerful expression.	brand_story/ChatGPT_Image_Jun_3_2026_07_16_30_PM.png	Premium Quality Fabric	Minimal & Modern Designs	Comfortable Everyday Wear	Community-Focused Brand	t	2026-06-21 21:04:37.148817+00	2026-06-22 08:45:15.103407+00
\.


--
-- Data for Name: orders_order; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_order (id, order_id, payment_method, payment_status, status, shipping_status, subtotal, shipping_charge, discount, total, courier_partner, tracking_number, estimated_delivery, shipped_at, delivered_at, created_at, updated_at, refund_status, refund_method, refund_reference, refunded_at, user_id) FROM stdin;
\.


--
-- Data for Name: orders_orderitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_orderitem (id, product_name, product_image, variant_id, sku, size, color, price, quantity, order_id) FROM stdin;
\.


--
-- Data for Name: orders_orderreturn; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_orderreturn (id, reason, comment, status, created_at, updated_at, order_id) FROM stdin;
\.


--
-- Data for Name: orders_shipmentevent; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_shipmentevent (id, status, message, created_at, order_id) FROM stdin;
\.


--
-- Data for Name: orders_shippingaddress; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_shippingaddress (id, full_name, phone, email, address_line_1, address_line_2, city, state, postal_code, country, created_at, updated_at, order_id) FROM stdin;
\.


--
-- Data for Name: payments_payment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.payments_payment (id, razorpay_order_id, razorpay_payment_id, amount, status, created_at, order_id) FROM stdin;
1	order_T4Qves9JymKUdM	pay_T4QwCKSli6G8K8	1.00	PAID	2026-06-21 21:41:47.409324+00	\N
2	order_T4Qz8ABSpQXeQP	pay_T4QzNYToM8VZNp	1.00	PAID	2026-06-21 21:45:04.642151+00	\N
\.


--
-- Data for Name: products_brand; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products_brand (id, created_at, updated_at, name, slug, logo, is_active) FROM stdin;
1	2026-06-21 21:09:21.341742+00	2026-06-21 21:09:21.341761+00	UT	ut	brands/logo.jpeg	t
\.


--
-- Data for Name: products_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products_category (id, created_at, updated_at, name, slug, image, is_active) FROM stdin;
1	2026-06-21 21:06:45.877841+00	2026-06-22 08:41:55.664864+00	Hoodies	hoodies	categories/Screenshot_2026-06-05_233546.png	t
3	2026-06-22 08:42:38.389581+00	2026-06-22 08:42:38.389603+00	Shirts	shirts	categories/Screenshot_2026-06-07_124011.png	t
4	2026-06-22 08:42:59.230929+00	2026-06-22 08:42:59.230953+00	Trousers	trousers	categories/Screenshot_2026-06-02_121419.png	t
2	2026-06-22 07:56:13.273924+00	2026-06-22 09:00:05.96903+00	T-shirts	t-shirts	categories/Screenshot_2026-06-05_232415.png	t
\.


--
-- Data for Name: products_color; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products_color (id, created_at, updated_at, name, hex_code) FROM stdin;
1	2026-06-21 21:07:08.167592+00	2026-06-21 21:07:08.167606+00	white	#FFFFFF
\.


--
-- Data for Name: products_inventorylog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products_inventorylog (id, created_at, updated_at, transaction_type, quantity, note, variant_id) FROM stdin;
\.


--
-- Data for Name: products_product; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products_product (created_at, updated_at, id, name, slug, description, material, minimum_order_quantity, status, is_featured, is_active, meta_title, meta_description, brand_id, category_id) FROM stdin;
2026-06-22 08:47:11.416747+00	2026-06-22 08:47:11.416761+00	43d232be-d06b-44b7-b963-8fca106023f1	Pure Cotton	pure-cotton	@	pure cotton	1	published	t	t	\N		1	3
2026-06-22 08:48:44.611868+00	2026-06-22 08:48:44.611882+00	2f762341-8651-4372-9fd2-79187f4cc21c	Linen_Club	linen_club	@	Lenin	1	published	t	t	\N		1	4
2026-06-22 08:50:54.108827+00	2026-06-22 08:51:28.808152+00	de3889cc-940c-44c3-a698-e91782b9ccef	Pure Cotton	pure-cotton-1	@	pure combed cotton	1	published	t	t	\N		1	1
2026-06-22 08:53:45.837877+00	2026-06-22 08:59:11.503464+00	2d9c407c-0183-4c36-aab1-3a4064dae43b	Pure Cotton	pure-cotton-2	@	pure combed cotton	1	published	t	t	\N		1	2
\.


--
-- Data for Name: products_productimage; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products_productimage (id, created_at, updated_at, image, is_primary, product_id) FROM stdin;
9	2026-06-22 08:47:11.523767+00	2026-06-22 08:47:11.523788+00	products/Screenshot_2026-05-11_204040.png	t	43d232be-d06b-44b7-b963-8fca106023f1
10	2026-06-22 08:48:44.876165+00	2026-06-22 08:48:44.876224+00	products/Screenshot_2026-06-07_125530.png	t	2f762341-8651-4372-9fd2-79187f4cc21c
12	2026-06-22 08:50:54.403648+00	2026-06-22 08:50:54.40367+00	products/Screenshot_2026-06-07_122713.png	f	de3889cc-940c-44c3-a698-e91782b9ccef
11	2026-06-22 08:50:54.321889+00	2026-06-22 08:51:28.809184+00	products/Screenshot_2026-06-05_232228.png	t	de3889cc-940c-44c3-a698-e91782b9ccef
13	2026-06-22 08:53:45.96056+00	2026-06-22 08:53:45.960584+00	products/Screenshot_2026-04-04_205435.png	t	2d9c407c-0183-4c36-aab1-3a4064dae43b
14	2026-06-22 08:59:11.586022+00	2026-06-22 08:59:11.586043+00	products/Screenshot_2026-04-04_205504.png	f	2d9c407c-0183-4c36-aab1-3a4064dae43b
\.


--
-- Data for Name: products_productvariant; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products_productvariant (id, created_at, updated_at, sku, wholesale_price, stock_quantity, is_active, color_id, product_id, size_id) FROM stdin;
4	2026-06-22 08:47:11.524913+00	2026-06-22 08:47:11.524926+00	1	499.00	0	t	1	43d232be-d06b-44b7-b963-8fca106023f1	1
5	2026-06-22 08:48:44.877413+00	2026-06-22 08:48:44.877427+00	2	599.00	1	t	1	2f762341-8651-4372-9fd2-79187f4cc21c	1
6	2026-06-22 08:50:54.404796+00	2026-06-22 08:50:54.404809+00	4	499.00	0	t	1	de3889cc-940c-44c3-a698-e91782b9ccef	1
7	2026-06-22 08:53:45.961604+00	2026-06-22 08:53:45.961617+00	3	499.00	0	t	1	2d9c407c-0183-4c36-aab1-3a4064dae43b	1
\.


--
-- Data for Name: products_size; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products_size (id, created_at, updated_at, name, sort_order) FROM stdin;
1	2026-06-21 21:07:37.288223+00	2026-06-21 21:11:02.006501+00	M	1
\.


--
-- Data for Name: wishlist_wishlist; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.wishlist_wishlist (id, created_at, product_id, user_id) FROM stdin;
\.


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 1, false);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 3, true);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 1, false);


--
-- Name: accounts_userprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_userprofile_id_seq', 3, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 100, true);


--
-- Name: carts_cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.carts_cart_id_seq', 2, true);


--
-- Name: carts_cartitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.carts_cartitem_id_seq', 5, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 45, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 25, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 25, true);


--
-- Name: home_brandstory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.home_brandstory_id_seq', 1, true);


--
-- Name: orders_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_order_id_seq', 4, true);


--
-- Name: orders_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_orderitem_id_seq', 4, true);


--
-- Name: orders_orderreturn_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_orderreturn_id_seq', 1, false);


--
-- Name: orders_shipmentevent_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_shipmentevent_id_seq', 1, false);


--
-- Name: orders_shippingaddress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_shippingaddress_id_seq', 4, true);


--
-- Name: payments_payment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.payments_payment_id_seq', 2, true);


--
-- Name: products_brand_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_brand_id_seq', 1, true);


--
-- Name: products_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_category_id_seq', 4, true);


--
-- Name: products_color_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_color_id_seq', 1, true);


--
-- Name: products_inventorylog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_inventorylog_id_seq', 1, false);


--
-- Name: products_productimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_productimage_id_seq', 14, true);


--
-- Name: products_productvariant_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_productvariant_id_seq', 7, true);


--
-- Name: products_size_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_size_id_seq', 1, true);


--
-- Name: wishlist_wishlist_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.wishlist_wishlist_id_seq', 2, true);


--
-- Name: accounts_user accounts_user_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_email_key UNIQUE (email);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_phone_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_phone_key UNIQUE (phone);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_userprofile accounts_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_pkey PRIMARY KEY (id);


--
-- Name: accounts_userprofile accounts_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: carts_cart carts_cart_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carts_cart
    ADD CONSTRAINT carts_cart_pkey PRIMARY KEY (id);


--
-- Name: carts_cart carts_cart_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carts_cart
    ADD CONSTRAINT carts_cart_user_id_key UNIQUE (user_id);


--
-- Name: carts_cartitem carts_cartitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carts_cartitem
    ADD CONSTRAINT carts_cartitem_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: home_brandstory home_brandstory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.home_brandstory
    ADD CONSTRAINT home_brandstory_pkey PRIMARY KEY (id);


--
-- Name: orders_order orders_order_order_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_order_id_key UNIQUE (order_id);


--
-- Name: orders_order orders_order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_pkey PRIMARY KEY (id);


--
-- Name: orders_orderitem orders_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_pkey PRIMARY KEY (id);


--
-- Name: orders_orderreturn orders_orderreturn_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_orderreturn
    ADD CONSTRAINT orders_orderreturn_pkey PRIMARY KEY (id);


--
-- Name: orders_shipmentevent orders_shipmentevent_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_shipmentevent
    ADD CONSTRAINT orders_shipmentevent_pkey PRIMARY KEY (id);


--
-- Name: orders_shippingaddress orders_shippingaddress_order_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_shippingaddress
    ADD CONSTRAINT orders_shippingaddress_order_id_key UNIQUE (order_id);


--
-- Name: orders_shippingaddress orders_shippingaddress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_shippingaddress
    ADD CONSTRAINT orders_shippingaddress_pkey PRIMARY KEY (id);


--
-- Name: payments_payment payments_payment_order_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_order_id_key UNIQUE (order_id);


--
-- Name: payments_payment payments_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_pkey PRIMARY KEY (id);


--
-- Name: products_brand products_brand_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_brand
    ADD CONSTRAINT products_brand_name_key UNIQUE (name);


--
-- Name: products_brand products_brand_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_brand
    ADD CONSTRAINT products_brand_pkey PRIMARY KEY (id);


--
-- Name: products_brand products_brand_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_brand
    ADD CONSTRAINT products_brand_slug_key UNIQUE (slug);


--
-- Name: products_category products_category_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_category
    ADD CONSTRAINT products_category_name_key UNIQUE (name);


--
-- Name: products_category products_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_category
    ADD CONSTRAINT products_category_pkey PRIMARY KEY (id);


--
-- Name: products_category products_category_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_category
    ADD CONSTRAINT products_category_slug_key UNIQUE (slug);


--
-- Name: products_color products_color_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_color
    ADD CONSTRAINT products_color_name_key UNIQUE (name);


--
-- Name: products_color products_color_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_color
    ADD CONSTRAINT products_color_pkey PRIMARY KEY (id);


--
-- Name: products_inventorylog products_inventorylog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_inventorylog
    ADD CONSTRAINT products_inventorylog_pkey PRIMARY KEY (id);


--
-- Name: products_product products_product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_pkey PRIMARY KEY (id);


--
-- Name: products_product products_product_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_slug_key UNIQUE (slug);


--
-- Name: products_productimage products_productimage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_productimage
    ADD CONSTRAINT products_productimage_pkey PRIMARY KEY (id);


--
-- Name: products_productvariant products_productvariant_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_productvariant
    ADD CONSTRAINT products_productvariant_pkey PRIMARY KEY (id);


--
-- Name: products_productvariant products_productvariant_product_id_size_id_color_0bf60ce1_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_productvariant
    ADD CONSTRAINT products_productvariant_product_id_size_id_color_0bf60ce1_uniq UNIQUE (product_id, size_id, color_id);


--
-- Name: products_productvariant products_productvariant_sku_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_productvariant
    ADD CONSTRAINT products_productvariant_sku_key UNIQUE (sku);


--
-- Name: products_size products_size_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_size
    ADD CONSTRAINT products_size_name_key UNIQUE (name);


--
-- Name: products_size products_size_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_size
    ADD CONSTRAINT products_size_pkey PRIMARY KEY (id);


--
-- Name: carts_cartitem unique_cart_variant; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carts_cartitem
    ADD CONSTRAINT unique_cart_variant UNIQUE (cart_id, variant_id);


--
-- Name: wishlist_wishlist wishlist_wishlist_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist_wishlist
    ADD CONSTRAINT wishlist_wishlist_pkey PRIMARY KEY (id);


--
-- Name: wishlist_wishlist wishlist_wishlist_user_id_product_id_57695ed7_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist_wishlist
    ADD CONSTRAINT wishlist_wishlist_user_id_product_id_57695ed7_uniq UNIQUE (user_id, product_id);


--
-- Name: accounts_user_email_b2644a56_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_email_b2644a56_like ON public.accounts_user USING btree (email varchar_pattern_ops);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_phone_c603acdd_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_phone_c603acdd_like ON public.accounts_user USING btree (phone varchar_pattern_ops);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: carts_cartitem_cart_id_9cb0a756; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX carts_cartitem_cart_id_9cb0a756 ON public.carts_cartitem USING btree (cart_id);


--
-- Name: carts_cartitem_variant_id_e28ecc53; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX carts_cartitem_variant_id_e28ecc53 ON public.carts_cartitem USING btree (variant_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: orders_order_order_id_03d11293_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_order_order_id_03d11293_like ON public.orders_order USING btree (order_id varchar_pattern_ops);


--
-- Name: orders_order_user_id_e9b59eb1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_order_user_id_e9b59eb1 ON public.orders_order USING btree (user_id);


--
-- Name: orders_orderitem_order_id_fe61a34d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_orderitem_order_id_fe61a34d ON public.orders_orderitem USING btree (order_id);


--
-- Name: orders_orderreturn_order_id_cacfab29; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_orderreturn_order_id_cacfab29 ON public.orders_orderreturn USING btree (order_id);


--
-- Name: orders_ship_email_4011cf_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_ship_email_4011cf_idx ON public.orders_shippingaddress USING btree (email);


--
-- Name: orders_ship_phone_8eac5f_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_ship_phone_8eac5f_idx ON public.orders_shippingaddress USING btree (phone);


--
-- Name: orders_ship_postal__a6f271_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_ship_postal__a6f271_idx ON public.orders_shippingaddress USING btree (postal_code);


--
-- Name: orders_shipmentevent_order_id_674ff221; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_shipmentevent_order_id_674ff221 ON public.orders_shipmentevent USING btree (order_id);


--
-- Name: products_brand_name_8e67b7a6_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_brand_name_8e67b7a6_like ON public.products_brand USING btree (name varchar_pattern_ops);


--
-- Name: products_brand_slug_925fd11b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_brand_slug_925fd11b_like ON public.products_brand USING btree (slug varchar_pattern_ops);


--
-- Name: products_ca_is_acti_a2d000_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_ca_is_acti_a2d000_idx ON public.products_category USING btree (is_active);


--
-- Name: products_ca_slug_da4386_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_ca_slug_da4386_idx ON public.products_category USING btree (slug);


--
-- Name: products_category_name_0ecfb368_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_category_name_0ecfb368_like ON public.products_category USING btree (name varchar_pattern_ops);


--
-- Name: products_category_slug_c558efae_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_category_slug_c558efae_like ON public.products_category USING btree (slug varchar_pattern_ops);


--
-- Name: products_color_name_de566232_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_color_name_de566232_like ON public.products_color USING btree (name varchar_pattern_ops);


--
-- Name: products_inventorylog_variant_id_1035a442; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_inventorylog_variant_id_1035a442 ON public.products_inventorylog USING btree (variant_id);


--
-- Name: products_pr_is_acti_ca4d9a_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_pr_is_acti_ca4d9a_idx ON public.products_product USING btree (is_active);


--
-- Name: products_pr_sku_dcab68_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_pr_sku_dcab68_idx ON public.products_productvariant USING btree (sku);


--
-- Name: products_pr_slug_3edc0c_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_pr_slug_3edc0c_idx ON public.products_product USING btree (slug);


--
-- Name: products_pr_status_041708_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_pr_status_041708_idx ON public.products_product USING btree (status);


--
-- Name: products_pr_stock_q_989677_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_pr_stock_q_989677_idx ON public.products_productvariant USING btree (stock_quantity);


--
-- Name: products_product_brand_id_3e2e8fd1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_product_brand_id_3e2e8fd1 ON public.products_product USING btree (brand_id);


--
-- Name: products_product_category_id_9b594869; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_product_category_id_9b594869 ON public.products_product USING btree (category_id);


--
-- Name: products_product_slug_70d3148d_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_product_slug_70d3148d_like ON public.products_product USING btree (slug varchar_pattern_ops);


--
-- Name: products_productimage_product_id_e747596a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_productimage_product_id_e747596a ON public.products_productimage USING btree (product_id);


--
-- Name: products_productvariant_color_id_c213fea2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_productvariant_color_id_c213fea2 ON public.products_productvariant USING btree (color_id);


--
-- Name: products_productvariant_product_id_d9c22902; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_productvariant_product_id_d9c22902 ON public.products_productvariant USING btree (product_id);


--
-- Name: products_productvariant_size_id_b307fc69; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_productvariant_size_id_b307fc69 ON public.products_productvariant USING btree (size_id);


--
-- Name: products_productvariant_sku_1b692018_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_productvariant_sku_1b692018_like ON public.products_productvariant USING btree (sku varchar_pattern_ops);


--
-- Name: products_size_name_804ce9e8_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_size_name_804ce9e8_like ON public.products_size USING btree (name varchar_pattern_ops);


--
-- Name: wishlist_wishlist_product_id_2d08b75d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wishlist_wishlist_product_id_2d08b75d ON public.wishlist_wishlist USING btree (product_id);


--
-- Name: wishlist_wishlist_user_id_13f28b16; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wishlist_wishlist_user_id_13f28b16 ON public.wishlist_wishlist USING btree (user_id);


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_userprofile accounts_userprofile_user_id_92240672_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_user_id_92240672_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carts_cart carts_cart_user_id_bd0756c7_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carts_cart
    ADD CONSTRAINT carts_cart_user_id_bd0756c7_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carts_cartitem carts_cartitem_cart_id_9cb0a756_fk_carts_cart_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carts_cartitem
    ADD CONSTRAINT carts_cartitem_cart_id_9cb0a756_fk_carts_cart_id FOREIGN KEY (cart_id) REFERENCES public.carts_cart(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carts_cartitem carts_cartitem_variant_id_e28ecc53_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carts_cartitem
    ADD CONSTRAINT carts_cartitem_variant_id_e28ecc53_fk_products_ FOREIGN KEY (variant_id) REFERENCES public.products_productvariant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_order orders_order_user_id_e9b59eb1_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_user_id_e9b59eb1_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderitem orders_orderitem_order_id_fe61a34d_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_order_id_fe61a34d_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderreturn orders_orderreturn_order_id_cacfab29_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_orderreturn
    ADD CONSTRAINT orders_orderreturn_order_id_cacfab29_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_shipmentevent orders_shipmentevent_order_id_674ff221_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_shipmentevent
    ADD CONSTRAINT orders_shipmentevent_order_id_674ff221_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_shippingaddress orders_shippingaddress_order_id_da2e8a03_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_shippingaddress
    ADD CONSTRAINT orders_shippingaddress_order_id_da2e8a03_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_payment payments_payment_order_id_22c479b7_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_order_id_22c479b7_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_inventorylog products_inventorylo_variant_id_1035a442_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_inventorylog
    ADD CONSTRAINT products_inventorylo_variant_id_1035a442_fk_products_ FOREIGN KEY (variant_id) REFERENCES public.products_productvariant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product products_product_brand_id_3e2e8fd1_fk_products_brand_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_brand_id_3e2e8fd1_fk_products_brand_id FOREIGN KEY (brand_id) REFERENCES public.products_brand(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product products_product_category_id_9b594869_fk_products_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_category_id_9b594869_fk_products_category_id FOREIGN KEY (category_id) REFERENCES public.products_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_productimage products_productimag_product_id_e747596a_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_productimage
    ADD CONSTRAINT products_productimag_product_id_e747596a_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_productvariant products_productvari_product_id_d9c22902_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_productvariant
    ADD CONSTRAINT products_productvari_product_id_d9c22902_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_productvariant products_productvariant_color_id_c213fea2_fk_products_color_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_productvariant
    ADD CONSTRAINT products_productvariant_color_id_c213fea2_fk_products_color_id FOREIGN KEY (color_id) REFERENCES public.products_color(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_productvariant products_productvariant_size_id_b307fc69_fk_products_size_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_productvariant
    ADD CONSTRAINT products_productvariant_size_id_b307fc69_fk_products_size_id FOREIGN KEY (size_id) REFERENCES public.products_size(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wishlist_wishlist wishlist_wishlist_product_id_2d08b75d_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist_wishlist
    ADD CONSTRAINT wishlist_wishlist_product_id_2d08b75d_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wishlist_wishlist wishlist_wishlist_user_id_13f28b16_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist_wishlist
    ADD CONSTRAINT wishlist_wishlist_user_id_13f28b16_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict yicELkftehF3ePpJBR0K6nhnNNxaqmOFjTplZGGRgrJCeZrrEXfI7T8Pxuo7G41

