# Generated by Django 6.0.6 on 2026-06-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(default='OUR BRAND', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='brand_story/')),
                ('feature_1', models.CharField(blank=True, max_length=100)),
                ('feature_2', models.CharField(blank=True, max_length=100)),
                ('feature_3', models.CharField(blank=True, max_length=100)),
                ('feature_4', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand Story',
                'verbose_name_plural': 'Brand Story',
            },
        ),
    ]
