# Generated by Django 5.1.7 on 2026-05-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_admin_note_remove_order_customer_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='sku',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_APPROVED', 'Return Approved'), ('RETURN_REJECTED', 'Return Rejected'), ('RETURN_PICKED', 'Return Picked'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/products/'),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PICKED', 'Picked'), ('REFUNDED', 'Refunded')], default='REQUESTED', max_length=20),
        ),
    ]
