# Generated by Django 5.1.7 on 2026-05-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_method',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('BANK', 'Bank Transfer'), ('WALLET', 'Wallet'), ('CASH', 'Cash Adjustment')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='NOT_REQUESTED', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('PICKED', 'Picked'), ('RECEIVED', 'Received'), ('REFUNDED', 'Refunded')], default='REQUESTED', max_length=30),
        ),
    ]
