# Generated by Django 5.1.7 on 2026-05-25 06:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_id_alter_orderitem_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['-created_at'], 'verbose_name': 'Shipping Address', 'verbose_name_plural': 'Shipping Addresses'},
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shipmentevent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='full_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['postal_code'], name='orders_ship_postal__a6f271_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['phone'], name='orders_ship_phone_8eac5f_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['email'], name='orders_ship_email_4011cf_idx'),
        ),
    ]
