# Generated by Django 5.1.7 on 2026-05-25 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_id_alter_orderitem_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shippingaddress',
            name='orders_ship_postal__a6f271_idx',
        ),
        migrations.RemoveIndex(
            model_name='shippingaddress',
            name='orders_ship_phone_8eac5f_idx',
        ),
        migrations.RemoveIndex(
            model_name='shippingaddress',
            name='orders_ship_email_4011cf_idx',
        ),
    ]
