# Generated by Django 5.1.7 on 2026-05-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_shippingaddress_orders_ship_postal__a6f271_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['postal_code'], name='orders_ship_postal__a6f271_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['phone'], name='orders_ship_phone_8eac5f_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['email'], name='orders_ship_email_4011cf_idx'),
        ),
    ]
