# Generated by Django 6.0.5 on 2026-06-18 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_pincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pincode',
        ),
    ]
