# Generated by Django 6.0.6 on 2026-06-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='reserved_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
